# Generated by Django 5.1.1 on 2024-09-27 16:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logview", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Log",
            new_name="NgnixLog",
        ),
    ]
