# Generated by Django 5.1.1 on 2024-09-29 01:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logview", "0002_rename_log_ngnixlog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ngnixlog",
            name="request",
        ),
    ]
