# Generated by Django 5.1.1 on 2024-09-29 01:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logview", "0003_remove_ngnixlog_request"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ngnixlog",
            name="agent",
        ),
        migrations.RemoveField(
            model_name="ngnixlog",
            name="referrer",
        ),
    ]
